name: foli-decon-music-r44
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4.3
  - r-remotes
  - r-jsonlite
  - r-data.table
  - r-matrix
  - r-nnls
  - r-ggplot2
  - r-mcmcpack
  - bioconductor-toast
  - bioconductor-biobase
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
